## 넘파이 배열 정렬하기

- np.sort() : 원 행렬은 유지한 채 정렬 결과를 반환 (불변 처럼 다룸)
- ndarray.sort() : 원 행렬의 정렬 후 결과 반환은 없음 (가변 처럼 다룸)



In [3]:
import numpy as np

org_array = np.array([3, 1, 9, 5])
print("원본 행렬 : ", org_array)
sort_array1 = np.sort(org_array) #원 행렬은 유지!
print("sort_array1 : ", sort_array1)

sort_array2 = org_array.sort()
print("sort_array2 : ", sort_array2)

원본 행렬 :  [3 1 9 5]
sort_array1 :  [1 3 5 9]
sort_array2 :  None


In [5]:
#[::1]  : 확장된 슬라이싱, 역순으로 정렬한다.

sort_array1_desc = np.sort(org_array)[::-1]
print("역순?", sort_array1_desc)

역순? [9 5 3 1]


In [7]:
array2d = np.array([8, 12, 7, 1]).reshape(2, 2)
print(array2d)

#axis 가 0일 때가 행(row)
print(np.sort(array2d, axis=0))

#axis 가 1일 때가 열(column)
print(np.sort(array2d, axis=1))

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [10]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print("정렬 시 인덱스 재배열 결과는 :", sort_indices)


<class 'numpy.ndarray'>
정렬 시 인덱스 재배열 결과는 : [1 0 3 2]


In [12]:
#RDBMS : 관계형 데이터베이스 관리 시스템


name_array = np.array(['pcy','pcs','eut','koujin'])
score_array = np.array([78, 95, 84, 98])

# 0 1 2 3
# name_arrayname_array[0,2,1,3]

sort_indices_asc = np.argsort(score_array)
print("성적 오른차순 정렬 시 성적 인덱스 : ", sort_indices_asc)
print("성적 오름차순 정렬 결과 이름으로 출력 :", name_array[sort_indices_asc])

성적 오른차순 정렬 시 성적 인덱스 :  [0 2 1 3]
성적 오름차순 정렬 결과 이름으로 출력 : ['pcy' 'eut' 'pcs' 'koujin']


In [13]:
# 내적 : 두 텐서(벡터) 간의 관계를 나타내는 데이터

A = np.array([[1, 2],
            [3,4]])

transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n',  transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
