## 넘파이

머신러닝의 주요 알고리즘은 선형대수와 통계 등에 기반한다.

넘파이는 선형대수 관련 기능을 포함해 다양한 연산 기능을 제공한다.
또한 C/C++와 같은 저수준 언어 기반의 호환 API를 제공한다.
따라서 프로그램과 데이터를 주고받거나 API를 호출해 쉽게 통합할 수 있게 해준다.

넘파이는 배열 기반의 연산은 물론이고 다양한 데이터 핸들링 기능도 제공한다.
그러나 비슷한 역할을 수행하는 판다스의 함수들이 좀 더 직관적이어서
판다스로 대체하는 경우가 대부분이다.



In [1]:
# 넘파이 ndarray
import numpy as np



In [9]:
# 멤버가 될 값을 전달하여 배열 생성
array1 = np.array([1, 2, 3])
print("array1 타입 : " , type(array1))
print("array1 형태(행열) : " , array1.shape) # shape = 행열을 나타냄

array2 = np.array([[1, 2, 3],[2, 3, 4]])
print("array2 타입 :", type(array2))
print("array2 타입(행열) :", array2.shape)

# ndim 사용 (배열의 차원 수 or 배열의 축 수)
print(f"array1 배열은 {array1.ndim}차원이고, \
      array2 배열은 {array2.ndim}차원이다.")



array1 타입 :  <class 'numpy.ndarray'>
array1 형태(행열) :  (3,)
array2 타입 : <class 'numpy.ndarray'>
array2 타입(행열) : (2, 3)
array1 배열은 1차원이고, array2 배열은 2차원이다.


## 넘파이 배열의 데이터 타입

ndarray가 포함할 수 있는 데이터 타입

- 숫자형 int 
- 숫자형 unsigned int (부호가 없는 int = 양수)
- 숫자형 float
- 숫자형 complex  ( 크거나 정밀한 값을 위한! )
- 문자열
- 불리언


넘파이 배열 내 데이터 타입은 연산 특성상 같은 타입만 가능하다
배열 내 데이터 타입은 dtype 멤버 변수로 확인할 수 있다.

만약 자료형이 섞인 리스트를 넘파이 배열로 변환하게 되면,
자동 형 변환이 일어나게 된다.


In [13]:
list1 = [1, 2, 3]
print(type(list1))
array1= np.array(list1)
print(type(array1))
print(array1, array1.dtype)

# 정수는 int8, int16, int32 등으로 표현할 수 있다.

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)



<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64


### 넘파이 배열 내 타입 변경하기

astype() 메소드를 이용하면 타입 변경이 가능하다.

이는 메모리를 절약해야 하는 상황에 주로 사용한다.
단 메모리 손실이 프로그램에 어떤 영향을 끼칠지 고려할 필요는 있다.



In [14]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype("float64")
print(array_float, array_float.dtype)

array_int1 = array_float.astype("int32")
print(array_int1,array_int1.dtype)

[1. 2. 3.] float64
[1 2 3] int32


## ndarray 편리하게 생성하기

- arange() : 범위를 정해 배열 생성하기
- zeros() : 0으로 채워진 배열 생성하기
- ones() : 1로 채워진 배열 생성하기



In [25]:
sequence_array = np.arange(10)
print(sequence_array)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
sequence_array = sequence_array.reshape(2,5) # 재배열
print(sequence_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
zero_array = np.zeros((2,3)) # shape을 지정하여 생성
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
ones_array = np.ones((5, 2)) # 1로 채워진 배열을 5행 2열로 생성!
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## 넘파이 ndarray 인덱싱

넘파이 배열 인덱싱의 종류
- 특정 데이터만 추출 : 리스트, 튜플 등에서의 인덱싱과 동일
- 슬라이싱 : 리스트, 튜플에서의 슬라이싱과 동일
- 팬시 인덱싱 : 일정한 인덱싱 집합을 리스트 또는 배열 형태로 지정해 해당 위치에 있는 값 반환하기
- 불리언 인덱싱 : 특정 조건에 해당하는지 여부를 기반으로 배열 값 반환하기




In [46]:
array1 = np.arange(stop=10, start=1)
print(array1) 

print(array1[2])

#슬라이싱
print(array1[4:7])

#3행 3열로 바꿔보기
array1= array1.reshape(3,3)
print(array1)
print(array1[1, 0])  # 리스트 중첩과 달리 배열은 이렇게 한다.




[1 2 3 4 5 6 7 8 9]
3
[5 6 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
4


In [47]:
#퀴즈 : 1부터 12로 채워진 4행 3열짜리 배열을 만들고 6을 인덱싱하자 


array2 = np.arange(start=1 , stop = 13)
array2= array2.reshape(4,3)
print(array2)
print(array2[1,2])

#위의 문장을 잛게 아래처럼 줄일수도 있다.
print(np.arange(start=1 , stop = 13).reshape(4,3)[1,2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
6
6


In [60]:
# 슬라이싱 : 리스트, 튜플에서의 슬라이싱과 동일

array1 = np.arange(10)
print(array1[2:5]) # 슬라이싱을할때 원본에대한 영향은 없다 (복사본을 가져와 가공하는것!)
print(array1[:]) # 전체복사

print("-----------------------------")

array1 = array1.reshape(5, 2) 
print(array1)
print(array1[0:2, :1])

print("-----------------------------")

array2 = np.arange(9).reshape(3, 3)
print(array2[0:2, 1:])

[2 3 4]
[0 1 2 3 4 5 6 7 8 9]
-----------------------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0]
 [2]]
-----------------------------
[[1 2]
 [4 5]]


In [61]:
#팬시 인덱싱 : 일정한 인덱싱 집합을 리스트 또는 배열 형태로 지정해 해당 위치에 있는 값 반환하기

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2] # 0과 1행에서 인덱스 2번출력
print("array3 : ", array3)

array3 :  [3 6]


In [63]:
# 필터 역할을 하는 배열의 불린 인덱싱

array1 = np.arange(3, 9)

# 인덱싱 기호[] 안에서는 배열명을 요소로 취급
arrau1 = array1[array1 > 5]
print(array1)

array2 = np.array([False, True, True, True, False, True, False])
array2 = array2[array2]
print(array2)


[3 4 5 6 7 8]
[ True  True  True  True]


In [72]:
# 퀴즈 
# 1~12까지의 4행3열을 만든후  5와 11을 출력하여라 


array3 = np.arange(start=1 , stop = 13).reshape(4, 3)
array4 = array3[[1,3], 1]
print(array4)


[ 5 11]
