In [1]:
import pandas as pd


In [3]:
# 파일명만 쓰면 같은 위치에서 찾고
# 파일 경로를 함께 쓰면 해당 위치에서 찾는다

titanic_df = pd.read_csv("titanic_train.csv")
print(titanic_df.head(3)) # 위에서 3개까지만


   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  


## 판다스(pandas) 데이터 프레임

판다스는 csv와 같이 정형화된 데이터 형식을 데이터프레임으로 변환할 수 있다.

이때 사용하는 주요 메소드는 다음과 같다.

- head(x) : 맨 윗행에서부터 x개까지만 출력하겠다.
- shape : 멤버 변수로, 행렬 정보를 제공한다.
- info() : 데이터 건수와 데이터 타입, 누락(Null) 건수를 알 수 있다.
- describe() : 데이터에 대한 전반적인 통계를 얻을 수 있다(분포)
- value_counts() : 데이터 필드의 통계를 낼 수 있다.

In [4]:
titanic_df.shape

(891, 12)

In [5]:
titanic_df.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                 

In [6]:
titanic_df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [8]:
import numpy as np

col_name1 = ["coll"]
list1 = [1, 2, 3]

array1 = np.array(list1)
print("shape", array1.shape)

df_list1 = pd.DataFrame(list1, columns = col_name1)
print(df_list1)

df_list1 = pd.DataFrame(array1, columns = col_name1)
print(df_list1)

shape (3,)
   coll
0     1
1     2
2     3
   coll
0     1
1     2
2     3


In [9]:
# 3개의 칼럼명이 필요함.
col_name2=['col1', 'col2', 'col3']

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
list2 = [[1, 2, 3],
         [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape )
df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)


array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [17]:
# 자료형이나 키워드 이름을 변수명으로 쓰지 말자!

dict_data = {
     "칼럼1": [ 1, 11 ],
     "칼럼2": [ 2, 22 ],
     "칼럼3": [ 3, 33 ]
}
df_dict = pd.DataFrame(dict_data)

array3 = df_dict.values # 넘파이 배열로의 변호나 결과 반환

print(array3) # 넘파이 배열
print(array3.tolist()) # 넘파이 배열 to 파이썬 리스트

print(df_dict.to_dict()) # 판다스 데이터 프레임 to 팡썬 딕셔너리




[[ 1  2  3]
 [11 22 33]]
[[1, 2, 3], [11, 22, 33]]
{'칼럼1': {0: 1, 1: 11}, '칼럼2': {0: 2, 1: 22}, '칼럼3': {0: 3, 1: 33}}


In [18]:
titanic_df = pd.read_csv("titanic_train.csv")


In [19]:
# DF에 열 추가하기 방법
titanic_df["town"] = "usa"

In [20]:
print(titanic_df.head(5))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked town  
0      0         A/5 21171   7.2500   NaN        S  usa  
1      0          PC 17599  71.2833   C85        C  usa  
2      0  STON/O2. 3101282   7.9250   NaN        S  usa  
3      0            113803  53.1000  C123        S  usa  
4      0            373450   8

In [24]:
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']

In [26]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked town  Family_No  
0      0         A/5 21171   7.2500   NaN        S  usa          1  
1      0          PC 17599  71.2833   C85        C  usa          1  
2      0  STON/O2. 3101282   7.9250   NaN        S  usa          0

In [29]:
titanic_df = pd.read_csv("titanic_train.csv")

In [30]:
indexes = titanic_df.index
print(indexes)

print("배열 형태로 보여줘 : ", indexes.values)

RangeIndex(start=0, stop=891, step=1)
배열 형태로 보여줘 :  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233

In [32]:
# 넘파이 배열과 유사하게 단일 값 반환 및 슬라이싱 가능! (그러나 불변성!)

print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])
# indexes[5] = 10 이거하면 에러가 난다. 불변성이기 때문!

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


reset_index() 사용하면 0부터 순차적으로 올라가는 인덱스가 별도로 추가되는데, 
이는 인덱스 번호가 정상적으로 순차 값을 가지지 않을 경우에는 사용할 만 하다.



In [33]:
titanic_df[0:2]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [34]:
data = {'Name': ['Chulmin', 'Eunkyung','Jinwoong','Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
       }
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [40]:
data_df.iloc[0, 0]

'Chulmin'

In [42]:
data_df.loc['two', 'Year']

2016

In [44]:
titanic_df = pd.read_csv("titanic_train.csv")
tb = titanic_df[titanic_df['Age'] > 60]
print(tb) # 걸러지는 대신, 인덱스가 띄엄띄엄 된다
print(tb.reset_index()) # 인덱스를 새로 지정할 수 있다

     PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis   
483          484         1  